# Generated by Django 4.2.5 on 2024-06-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='pending', max_length=10),
        ),
    ]
