# Generated by Django 5.0.6 on 2024-07-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='review',
        ),
        migrations.AddField(
            model_name='demand',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
