# Generated by Django 5.0.6 on 2024-07-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_service_review_demand_requested_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
