# Generated by Django 5.0.6 on 2024-07-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_demand_end_time_demand_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='demand',
            field=models.IntegerField(default=0),
        ),
    ]
